### ISSUE TITLE
Add animated actor (human)

### ISSUE THREAD

**Issue by dmiklic** [romb-technologies/ariac_environment#3]
Add an human actor by following [these instructions](http://gazebosim.org/tutorials?tut=actor&cat=build_robot).

- check if the actor is visible in sensor readings.
- also check if we can get actor pose published on a topic

**Comment by filipkozlik** [comment]
Should the actor be added directly into ariac.world or as a model and then included?

**Comment by dmiklic** [comment]
If possible, I would prefer to have them as separate models.

**Comment by dmiklic** [comment]
Closed by ebe724e57479c869a3a388c88faf92c75a368aaf

**Comment by dmiklic** [comment]
Nice job @filipkozlik 
I have made two small changes to launch file names and parameters, so please make sure to update your repo by pulling from upstream/master
