### ISSUE TITLE
REST request issue when accessing api.ignitionfuel.org

### ISSUE THREAD

**Issue by TKomericki** [romb-technologies/ariac_environment#9]
There is an issue when running ariac environment on gazebo, apparently there is no connection with api.ignitionfuel.org which results in an empty environment opening in gazebo.
The question has been posted on this link: http://answers.gazebosim.org/question/22262/error-in-rest-request-for-accessing-apiignitionorg/

Here is the screenshot of the problem, which can also be found on the link above:
![gazebo greska](https://user-images.githubusercontent.com/32905028/55884466-6645e200-5ba8-11e9-87a0-01540b132785.png)

**Comment by dmiklic** [comment]
As per [this answer](http://answers.gazebosim.org/question/22263/error-in-rest-request-for-accessing-apiignitionorg/), there are two solutions:

- upgrade to Gazebo >= 9.1.0
- Update the server in `~/.ignition/fuel/config.yaml` from `https://api.ignitionfuel.org` to `https://api.ignitionrobotics.org`

This is unrelated to the invisible ariac environment, issue #10.
